[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "omnicare_telehealth_patient_outcomes_analytics"
version = "1.0.0"
description = "Digital Health & Telehealth Operations Data Warehouse: Virtual consultation wait times, e-prescription adherence, in-person escalation rates, and video/audio QoS scores."
readme = "README.md"
authors = [
    { name = "Abdussatar", email = "satarabdus692@gmail.com" }
]
license = { text = "MIT" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Information Analysis"
]
